[build]
  command = "npm run build"
  publish = "dist/ids-dashboard/browser"
  functions = "functions"

[dev]
  command = "npm start"
  port = 4200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = "dist/ids-dashboard/browser"
